data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data <- data[data$Date >= "2007-02-01" & data$Date <= "2007-02-02",]
data$DateTime <- strptime(paste(data$Date, data$Time),"%Y-%m-%d %H:%M:%S")
png(file = "plot4.png")
par(mfrow = c(2,2))
plot(data$DateTime,data$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
plot(data$DateTime,data$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(data$DateTime,data$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
points(data$DateTime,data$Sub_metering_2, type = "l", col = "red")
points(data$DateTime,data$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, bty = "n")
plot(data$DateTime,data$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()
